global:
  hosts:
    iam: iam.hall144-eiap.ews.gic.ericsson.se
    gas: gas.hall144-eiap.ews.gic.ericsson.se
    os: os.hall144-eiap.ews.gic.ericsson.se
    appmgr: appmgr.hall144-eiap.ews.gic.ericsson.se
    adc: adc.hall144-eiap.ews.gic.ericsson.se
    th: th.hall144-eiap.ews.gic.ericsson.se
    ta: ta.hall144-eiap.ews.gic.ericsson.se
    ml: ml.hall144-eiap.ews.gic.ericsson.se
    la: la.hall144-eiap.ews.gic.ericsson.se
  registry:
    url: DOCKER_REGISTRY_REPLACE
    username: USERNAME_REPLACE
    password: 'PASSWORD_REPLACE'
  support:
    ipv6:
      enabled: false
  timezone: UTC
  createClusterRoles: true
  security:
    tls:
      enabled: true
tags:
  adc: true
  dmm: true
  th: false
  eas: false
  ch: false
  appmgr: false
  ta: false
  os: false
  pmh: false
  ml: false
eric-cloud-native-base:
  eric-data-search-engine-curator:
    cronjob:
      curator:
        schedule: 0 */2 * * *
    actions: ''
  eric-sec-access-mgmt:
    accountManager:
      enabled: false
      inactivityThreshold: 9999
    replicaCount: 2
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 15Gi
    sftp:
      username: dummy
      password: dummy
  eric-log-transformer:
    egress:
      syslog:
        enabled: false
        remoteHosts: []
  eric-data-search-engine:
    service:
      network:
        protocol:
          IPv6: false
    persistence:
      data:
        persistentVolumeClaim:
          size: 10Gi
  eric-data-object-storage-mn:
    brAgent:
      properties:
        backup_data_path: bucket1/data1.txt
    persistentVolumeClaim:
      size: 75Gi
  eric-fh-snmp-alarm-provider:
    sendAlarm: false
    service:
      loadBalancerIP: 10.156.77.157
      annotations:
        cloudProviderLB: {}
eric-oss-common-base:
  sessionTokens:
    maxSessionDurationSecs: 36000
    maxIdleTimeSecs: 1800
  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: 10.156.77.157
      annotations:
        cloudProviderLB: {}
    externalTrafficPolicy: Cluster
  system-user:
    credentials:
      username: system-user
      password: Ericsson123!
  gas:
    defaultUser:
      username: gas-user
      password: Ericsson123!
  eric-eo-usermgmt:
    replicaCount: 2
  eric-eo-usermgmt-ui:
    replicaCount: 2
  eric-oss-ddc:
    autoUpload:
      enabled: false
eric-topology-handling:
  eric-oss-common-topology-svc:
    eric-oss-cmn-topology-svc-core:
      defaultUser:
        username: cts-user
        password: Ericsson123!
      useGasHost:
        enabled: true
eric-oss-oran-support:
  eric-oss-a1-policy-mngmt-svc:
    defaultUser:
      username: a1-user
      password: DefaultP12345!
eric-oss-ericsson-adaptation:
  eric-oss-ran-topology-adapter:
    rtaUser:
      username: rta-user
      password: Ericsson123!
eric-oss-config-handling:
  cps-user:
    credentials:
      username: cps-user
      password: Ericsson123!
  dmi-user:
    credentials:
      username: dmi-user
      password: Ericsson123!
eric-oss-adc:
  ingress:
    tls:
      secretName: ves-tls-secret
  stubs:
    enabled: true
  preHookJobs:
    enabled: true
eric-oss-task-automation-ae:
  defaultUser:
    username: fa-user
    password: Ericsson123!
ml-execution-env:
  credentials:
    objectStorage:
      jobUser:
        password: objectStorageJobUserPassword
      serviceUser:
        password: objectStorageServiceUserPassword
    containerRegistry:
      username: dockeruser
      password: dockerpassword
    database:
      custom:
        password: modellcmpasswd
      metrics:
        password: exporter
      replica:
        password: replica
      super:
        password: Postgres1#
eric-oss-ml-execution-env:
  credentials:
    objectStorage:
      jobUser:
        password: objectStorageJobUserPassword
      serviceUser:
        password: objectStorageServiceUserPassword
    containerRegistry:
      username: dockeruser
      password: dockerpassword
    database:
      custom:
        password: modellcmpasswd
      metrics:
        password: exporter
      replica:
        password: replica
      super:
        password: Postgres1#
eric-fh-snmp-alarm-provider:
  service:
    loadBalancerIP: 10.156.77.157
stubs:
  enabled: true
preHookJobs:
  enabled: true