apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumes-access-users
rules:
- apiGroups:
  - '*'
  resources:
  - nodes
  - persistentvolumes
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'